### ISSUE TITLE
There is no support of fragment

### ISSUE THREAD

**Issue by Yukooo** [sw926/ImageFileSelector#1]
1) Please add 
**public void takePhoto(Fragment fragment)**
and
**public void selectorImage(Fragment fragment)**
to the ImageFileSelector class
to call fragment.startActivityForResult

since if you call activity.startActivityForResult we will never get a callback onActivityResult in our fragment
2) Is it possible to replace all comments and docs with English words

**Comment by yulongsun007** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: win.yulongsun.demoimagepicker, PID: 7967
                                                                             java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1793, result=-1, data=Intent { dat=content://com.google.android.apps.docs.storage/document/acc=1;doc=6 flg=0x1 }} to activity {win.yulongsun.demoimagepicker/win.yulongsun.demoimagepicker.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                                 at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
                                                                                 at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                                                                                 at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                                 at java.io.File.fixSlashes(File.java:183)
                                                                                 at java.io.File.<init>(File.java:130)
                                                                                 at com.sw926.imagefileselector.ImageFileSelector.handleResult(ImageFileSelector.java:116)
                                                                                 at com.sw926.imagefileselector.ImageFileSelector.access$100(ImageFileSelector.java:11)
                                                                                 at com.sw926.imagefileselector.ImageFileSelector$1.onSuccess(ImageFileSelector.java:26)
                                                                                 at com.sw926.imagefileselector.ImagePickHelper.onActivityResult(ImagePickHelper.java:71)
                                                                                 at com.sw926.imagefileselector.ImageFileSelector.onActivityResult(ImageFileSelector.java:87)
                                                                                 at win.yulongsun.demoimagepicker.MainActivity.onActivityResult(MainActivity.java:102)
                                                                                 at android.app.Activity.dispatchActivityResult(Activity.java:6428)
                                                                                 at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                                                                                 at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
                                                                                 at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sw926** [comment]
I will add support of fragment soon

**Comment by imkarl** [comment]
Can suppport android.app.Fragment?
